import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import AppShell from '../components/AppShell';
import PageHeader from '../components/ui/PageHeader';
import Card, { CardTitle } from '../components/ui/Card';
import Button from '../components/ui/Button';
import Badge from '../components/ui/Badge';
import Progress from '../components/ui/Progress';
import { startRescue } from '../services/learningApi';
import { Flame, Clock, CheckCircle2, AlertTriangle, RotateCcw, Sparkles, ArrowRight, ShieldCheck } from 'lucide-react';

export default function RescueMode() {
  const navigate = useNavigate();
  const [topic, setTopic] = useState('');
  const [notes, setNotes] = useState('');
  const [session, setSession] = useState(null);
  const [answers, setAnswers] = useState({});
  const [seconds, setSeconds] = useState(300);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  useEffect(() => {
    if (!session || seconds <= 0) return;
    const timer = setInterval(() => setSeconds((v) => Math.max(0, v - 1)), 1000);
    return () => clearInterval(timer);
  }, [session, seconds]);

  const handleLaunch = async (e) => {
    e.preventDefault();
    if (!topic.trim()) return setError('Enter a topic to rescue.');
    setLoading(true);
    setError('');

    try {
      const data = await startRescue({ topic, notes });
      setSession(data);
      setSeconds(300);
    } catch (err) {
      setError(err.response?.data?.message || 'Failed to initialize Rescue session.');
    } finally {
      setLoading(false);
    }
  };

  const answeredCount = Object.keys(answers).length;
  const totalQuestions = session?.questions?.length || 3;
  const readinessResult = Math.round((answeredCount / totalQuestions) * 100);

  const formatTimer = (s) => `${Math.floor(s / 60)}:${String(s % 60).padStart(2, '0')}`;

  return (
    <AppShell>
      <div className="space-y-8 animate-fade-in">
        <PageHeader
          badge={<Badge variant="yellow" icon={Flame}>Emergency Revision</Badge>}
          title="5-Minute Rescue Mode"
          description="Exam in 10 minutes? Rapid zero-fluff summary of Must Know formulas, Common Traps, and rapid recall checks."
        />

        {/* Input Form */}
        {!session ? (
          <Card hoverEffect={false} className="max-w-2xl mx-auto p-8 space-y-6">
            <div className="flex items-center gap-3">
              <div className="w-12 h-12 rounded-2xl bg-amber-100 text-amber-700 flex items-center justify-center">
                <Flame size={24} />
              </div>
              <div>
                <h3 className="font-display font-extrabold text-xl text-slate-900">Select Topic to Rescue</h3>
                <p className="text-xs text-slate-500">Fast 5-minute rapid recall pack generated by AI.</p>
              </div>
            </div>

            <form onSubmit={handleLaunch} className="space-y-4">
              <div>
                <label className="label">Topic Name</label>
                <input
                  type="text"
                  placeholder="e.g. Subnetting & IP Addressing, Deadlocks, Organic Reactions"
                  className="input-field"
                  value={topic}
                  onChange={(e) => setTopic(e.target.value)}
                />
              </div>

              <div>
                <label className="label">Optional Specific Notes / Syllabus Text</label>
                <textarea
                  placeholder="Paste the key formula or concept you keep forgetting..."
                  className="input-field min-h-[90px]"
                  value={notes}
                  onChange={(e) => setNotes(e.target.value)}
                />
              </div>

              {error && <p className="text-xs font-bold text-rose-600">{error}</p>}

              <Button type="submit" loading={loading} variant="accent" className="w-full py-3.5 text-base shadow-gold">
                Start 5-Minute Rescue Timer <Clock size={18} />
              </Button>
            </form>
          </Card>
        ) : (
          /* Active Rescue Session */
          <div className="space-y-6 max-w-4xl mx-auto">
            {/* Top Bar with Timer */}
            <div className="p-4 rounded-2xl bg-gradient-to-r from-amber-500 via-orange-500 to-rose-500 text-white flex items-center justify-between shadow-lg">
              <div className="flex items-center gap-3">
                <Flame size={24} />
                <div>
                  <h3 className="font-display font-bold text-lg text-white">5-Minute Rescue: {topic}</h3>
                  <p className="text-xs text-amber-100">Rapid Recall Mode Active</p>
                </div>
              </div>

              <div className="px-4 py-2 rounded-xl bg-white/20 backdrop-blur border border-white/30 font-display font-extrabold text-xl">
                ⏱ {formatTimer(seconds)}
              </div>
            </div>

            {/* Sections */}
            <div className="grid md:grid-cols-2 gap-6">
              {/* 1. MUST KNOW */}
              <Card hoverEffect={false} className="p-6">
                <h4 className="font-display font-bold text-sm text-[#218DAE] uppercase tracking-wider mb-3 flex items-center gap-2">
                  <Sparkles size={16} /> 1. MUST KNOW CONCEPTS
                </h4>
                <ul className="space-y-2 text-xs text-slate-700">
                  {(session.priorityConcepts || [
                    'Mutual Exclusion: Only one process can use resource at a time.',
                    'Hold and Wait: Process holds resource while requesting another.',
                    'Banker\'s Algorithm: Avoids deadlocks by checking safe state.',
                  ]).map((item, idx) => (
                    <li key={idx} className="p-3 rounded-xl bg-[#F0F9FC] border border-[#2BBBD7]/20 font-semibold">
                      ✓ {item}
                    </li>
                  ))}
                </ul>
              </Card>

              {/* 2. COMMON MISTAKES */}
              <Card hoverEffect={false} className="p-6">
                <h4 className="font-display font-bold text-sm text-rose-600 uppercase tracking-wider mb-3 flex items-center gap-2">
                  <AlertTriangle size={16} /> 2. COMMON TRAPS & MISTAKES
                </h4>
                <ul className="space-y-2 text-xs text-slate-700">
                  {(session.weakAreas || [
                    'Confusing Deadlock with Starvation (Starvation is indefinite delay).',
                    'Ignoring Preemption allowed condition.',
                  ]).map((item, idx) => (
                    <li key={idx} className="p-3 rounded-xl bg-rose-50 border border-rose-200 font-semibold text-rose-950">
                      ⚠️ {item}
                    </li>
                  ))}
                </ul>
              </Card>
            </div>

            {/* 3. RAPID RECALL & FINAL CHALLENGE */}
            <Card hoverEffect={false} className="p-6 space-y-4">
              <h4 className="font-display font-bold text-sm text-slate-900 uppercase tracking-wider flex items-center gap-2">
                <CheckCircle2 size={16} className="text-emerald-600" /> 3. RAPID RECALL CHALLENGE
              </h4>

              <div className="space-y-3">
                {(session.questions || [
                  { question: 'What is the main difference between deadlock prevention and avoidance?', answer: 'Prevention negates one of 4 conditions; Avoidance uses safety algorithms dynamically.' },
                ]).map((q, idx) => (
                  <div key={idx} className="p-4 rounded-xl bg-slate-50 border border-slate-200 space-y-2">
                    <p className="font-bold text-xs text-slate-800">{idx + 1}. {q.question}</p>
                    <button
                      onClick={() => setAnswers({ ...answers, [idx]: true })}
                      className="px-3 py-1.5 rounded-lg bg-white border border-slate-200 text-xs font-semibold text-slate-700 hover:border-[#218DAE] transition"
                    >
                      {answers[idx] ? '✓ Self-Verified' : 'Reveal Answer & Check'}
                    </button>

                    {answers[idx] && (
                      <p className="p-3 rounded-lg bg-emerald-50 text-xs text-emerald-950 font-semibold border border-emerald-200">
                        {q.answer}
                      </p>
                    )}
                  </div>
                ))}
              </div>
            </Card>

            {/* Are You Ready Result */}
            <Card hoverEffect={false} className="p-6 text-center space-y-4 bg-slate-900 text-white">
              <Badge variant="yellow">ARE YOU READY FOR YOUR EXAM?</Badge>
              <div className="flex items-center justify-center gap-4">
                <span className="font-display font-black text-4xl text-[#FFD758]">{readinessResult}%</span>
                <span className="text-xs text-slate-300 text-left">Rapid Recall<br />Completion Rate</span>
              </div>

              <div className="flex justify-center gap-3 pt-2">
                <Button onClick={() => { setSession(null); setAnswers({}); }} variant="secondary" icon={RotateCcw}>
                  Rescue Another Topic
                </Button>
                <Button onClick={() => navigate('/dashboard')} variant="accent" icon={ArrowRight}>
                  Return to Dashboard
                </Button>
              </div>
            </Card>
          </div>
        )}
      </div>
    </AppShell>
  );
}
